mysite/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', TemplateView.as_view(template_name="contact/contact.html")),
    path('news/', include('news.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', v.signup_view, name='register'),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

mysite/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

mysite/cart/models.py
from django.db import models

# Create your models here.

mysite/cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')
def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')
def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% block title %}
  Your basket of goods
{% endblock %}
{% block content %}
  <h1 style="color:#FAEBD7">Your basket of goods</h1>
  <table class="cart" style="color:#FAEBD7">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Amount</th>
        <th>Delete</th>
        <th>Full price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
            <form action="{% url 'cart:CartAdd' product.id %}" method="post" class="add">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.update }}
              {% csrf_token %}
              <input type="submit" value="Refresh">
            </form>
          </td>
            <td><a href="{% url 'cart:CartRemove' product.id %}">Delete</a></td>
            <td class="num">{{ item.price }} tg.</td>
            <td class="num">{{ item.total_price }} tg.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} tg.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right" style="color:#FAEBD7">
    <a href="{% url 'shop:ProductList'%}" class="btn btn-info btn-lg" style="color:#FAEBD7">Continue Shopping</a>
    <a href="{% url 'orders:OrderCreate' %}" class="btn btn-primary btn-lg" style="color:#FAEBD7">Checkout</a>
  </p>
{% endblock %}