mysite/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', TemplateView.as_view(template_name="contact/contact.html")),
    path('news/', include('news.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', v.signup_view, name='register'),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('orders.urls', 'orders'), namespace='orders')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
]

mysite/shop/models.py
from django.db import models
from django.urls import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория", on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
          return reverse('shop:ProductDetail', args=[self.id, self.slug])

mysite/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })

def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html',
                             {'product': product,
                              'cart_product_form': cart_product_form})
def contact(request):
    return render (request, 'contact/basic.html')

mysite/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- Styles -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <style>
    body{
      background: url('http://imagesait.ru/photos/aHR0cDovLzM2NXBzZC5ydS9pbWFnZXMvYmFja2dyb3VuZHMvYmctZGFyay00Nzg0LmpwZw==/chrnye-fony.jpg)');
    }
    .headerr{
      background: url('https://st2.depositphotos.com/1013886/10127/i/950/depositphotos_101275930-stock-photo-healthy-fruits-background.jpg');

    }
    h1, h2{
      color: white;
    }
  </style>
</head>
<body>
  <section class="headerr">
      <section class="top-bar-section">
      <ul class="rigth">
        {% if user.is_authenticated %}
          <li>&nbsp;&nbsp;<a href="{% url 'logout' %}" class="btn btn-dark btn-lg" >Logout {{ user.get_username }}</a></li>
        {% else %}
          <li>&nbsp;&nbsp;<a href="{% url 'login' %}" class="btn btn-primary btn-lg" >login</a></li>
        {% endif %}
      </ul>
     </section>
    <div class="container" >
      <p>
        <a href="/" class="btn btn-success btn-lg" > Main Page</a>
        <a href="/news" class="btn btn-warning btn-lg">Salles &raquo;</a>
        <a href="/contact" class="btn btn-info btn-lg">Contact </a>
      </p>
      <p>   &nbsp;&nbsp;&nbsp;&nbsp;
      </p>
    </div>
   </div>
 </section>
  <section id="header">
    <div class="top container">
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              Your basket:
--               <a href="{% url 'cart:CartDetail' %}">
                {{ total_items }} goods {{ cart.get_total_price }} tg.
              </a>
            {% else %}
             The cart is empty
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>





<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>